/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package textfilefetchcontent;
    import java.io.File;
    import javax.swing.JOptionPane;
    import java.io.BufferedReader;
    import java.io.FileInputStream;
    import java.io.FileWriter;
    import java.io.InputStreamReader;
/**
 *
 * @author CHAD
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateFile = new javax.swing.JButton();
        btnAddContent = new javax.swing.JButton();
        btnReadContent = new javax.swing.JButton();
        lblOutput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCreateFile.setText("Step 1: Create File");
        btnCreateFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateFileActionPerformed(evt);
            }
        });

        btnAddContent.setText("Step 2: Add Content ");
        btnAddContent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddContentActionPerformed(evt);
            }
        });

        btnReadContent.setText("Step 3: Read Content");
        btnReadContent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadContentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReadContent)
                    .addComponent(btnAddContent)
                    .addComponent(btnCreateFile))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btnCreateFile)
                .addGap(32, 32, 32)
                .addComponent(btnAddContent)
                .addGap(29, 29, 29)
                .addComponent(btnReadContent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateFileActionPerformed
    File Textfile = new File("textfile.txt");
    try
    {
    Textfile.createNewFile();
    lblOutput.setText("File has been created");
    }// TODO add your handling code here:
    catch (Exception Ex)
    {
        JOptionPane.showMessageDialog(null, Ex);
    }
    }//GEN-LAST:event_btnCreateFileActionPerformed

    private void btnAddContentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddContentActionPerformed
try 
{
String strfilename = "textfile.txt";
FileWriter fw = new FileWriter(strfilename,true);
fw.write("This is the content inside the text file\n");
fw.close();
lblOutput.setText("content has been written to the file");
}
catch (Exception Ex)
{
JOptionPane.showMessageDialog(null,Ex);
}// TODO add your handling code here:

    }//GEN-LAST:event_btnAddContentActionPerformed

    private void btnReadContentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadContentActionPerformed
String strline;
BufferedReader brReader = null;
InputStreamReader isrReader = null;
try
{
    FileInputStream fisFin = new FileInputStream("textfile.txt");
    isrReader = new InputStreamReader(fisFin);
    brReader = new BufferedReader(isrReader);
    while((strline = brReader.readLine())!= null)
    {lblOutput.setText("Content has been read from the file");
    JOptionPane.showMessageDialog(null,strline);
    }
brReader.close();
isrReader.close();
fisFin.close();
}
catch (Exception Ex)
{
    JOptionPane.showMessageDialog(null,Ex);
}
// TODO add your handling code here:
    }//GEN-LAST:event_btnReadContentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddContent;
    private javax.swing.JButton btnCreateFile;
    private javax.swing.JButton btnReadContent;
    private javax.swing.JLabel lblOutput;
    // End of variables declaration//GEN-END:variables
}
