/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FA1Project;
import java.io.FileWriter;
import java.io.IOException;// Import the IOException class to handle errors
import java.io.Console;


/**
 *
 * @author ALPHA
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public Registration() {
        initComponents();
        lblFirstNameError.setVisible(false);
        lblSurnameError.setVisible(false);
        lblMarkError.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblFirstNameError = new javax.swing.JLabel();
        lblSurnameError = new javax.swing.JLabel();
        lblMarkError = new javax.swing.JLabel();
        lblOutput = new javax.swing.JLabel();
        txtSurname = new javax.swing.JTextField();
        txtMark = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        Fname = new javax.swing.JLabel();
        Sname = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblFirstName1 = new javax.swing.JLabel();

        jLabel5.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration");
        setBackground(new java.awt.Color(0, 0, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFirstName.setBorder(null);
        getContentPane().add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 160, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("08HA2001794");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MAKGOTLHO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ALPHA");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Registration Form ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        lblFirstNameError.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFirstNameError.setForeground(new java.awt.Color(255, 0, 0));
        lblFirstNameError.setText("First Name can't be empty");
        getContentPane().add(lblFirstNameError, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 200, 20));

        lblSurnameError.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSurnameError.setForeground(new java.awt.Color(255, 0, 0));
        lblSurnameError.setText("Surname can't be empty");
        getContentPane().add(lblSurnameError, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 180, 20));

        lblMarkError.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMarkError.setForeground(new java.awt.Color(255, 0, 0));
        lblMarkError.setText("Percentage Mark can't be empty");
        getContentPane().add(lblMarkError, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 210, 20));

        lblOutput.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblOutput.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 460, 20));

        txtSurname.setBorder(null);
        getContentPane().add(txtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 160, -1));

        txtMark.setBorder(null);
        getContentPane().add(txtMark, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 160, -1));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, -1, -1));

        Fname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Fname.setForeground(new java.awt.Color(0, 204, 204));
        Fname.setText("FIRST NAME");
        getContentPane().add(Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 125, -1));

        Sname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Sname.setForeground(new java.awt.Color(0, 204, 204));
        Sname.setText("SURNAME");
        getContentPane().add(Sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 125, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("PERCENTAGE MARK");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 190, 36));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("RETURN");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALPHA\\Pictures\\Saved Pictures\\features_v-piano_technology.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 560));

        lblFirstName1.setText("jLabel3");
        getContentPane().add(lblFirstName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
    String firstName, surname, stringmark;
    Long time;
    Boolean thereAreErrors = false;
    
    firstName = txtFirstName.getText();
    surname = txtSurname.getText();
    stringmark = txtMark.getText();
            
    //check firstName
    if(firstName.isEmpty()){
      lblFirstNameError.setVisible(true);  
      thereAreErrors = true;
    }
    else{
    lblFirstNameError.setVisible(false);    
    }
    //check surname
    if (surname.isEmpty()){
        lblSurnameError.setVisible(true);
        thereAreErrors = true;
    }
    else{
        lblSurnameError.setVisible(false);
    }
    //check Pmark
    if (stringmark.isEmpty()){
        lblMarkError.setVisible(true);
        lblMarkError.setText("Time cannot be empty");
        thereAreErrors = true;
    }
    else{
        lblMarkError.setVisible(false);
         try{
       time = Long.valueOf(stringmark);
    }
    catch(Exception e){
        lblMarkError.setText("Invalid Mark Input");
         lblMarkError.setVisible(true);
         thereAreErrors = true;
         }
    }

 //checking that the mark input is a natural   
            String stringMark;
 if(Long.valueOf(stringmark) >= 0){
    lblOutput.setText("is a natural number that is greater than or equal to zero"); 
 }else{
     lblOutput.setVisible(false);
     
 }
 if(Long.valueOf(stringmark) <= 100){
     lblOutput.setText("is a natural number that is less than or equal to one hundred"); 
 }else{
     lblOutput.setVisible(false);
 }
    
    
     if(!thereAreErrors){
        System.out.println("There are no errors"); 
        
//proceed withsaving data
    String toSave = firstName+";"+surname+";"+stringmark+"\n";
    try{
    FileWriter myWriter = new FileWriter("student.txt",true);
    myWriter.write(toSave);
    myWriter.close();
    System.out.println("Successfully wrote to the file.");
    }catch (IOException e) {
    System.out.println("An error occurred");
    e.printStackTrace();
    }
     
   
//    try{        
//        System.out.println("First name: " +firstName);
//    }
//    catch(Exception e){
//    thereAreErrors = true;
//    System.out.println("First name Error" + e);
//    }
//    
//    try{
//        
//    }
//    catch(Exception e){
//    thereAreErrors = true;
//     System.out.println("Surname Error" + e);
//    }
//    try{
//       time = Long.valueOf(txtFirstName.getText());
//    }
//    catch(Exception e){
//    thereAreErrors = true;
//     System.out.println("Time Error" + e);
//    }
//    
//    if(!thereAreErrors){
//         System.out.println("There are no errors"); 
//        //proceed withsaving data
//         
//    }  
    }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       redirectMainPage();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void redirectMainPage(){
        frmMain frmMain = new frmMain();
        frmMain.show();
        this.setVisible(false);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fname;
    private javax.swing.JLabel Sname;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblFirstName1;
    private javax.swing.JLabel lblFirstNameError;
    private javax.swing.JLabel lblMarkError;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JLabel lblSurnameError;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtMark;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables
}

 

