/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package praxis.pkg1.hpx100.pkg1.sa1;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author CHAD
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtInputLength = new javax.swing.JTextField();
        txtInputWidth = new javax.swing.JTextField();
        txtInputHeight = new javax.swing.JTextField();
        lblArea = new javax.swing.JLabel();
        lblLength = new javax.swing.JLabel();
        lblWidth = new javax.swing.JLabel();
        lblHeight = new javax.swing.JLabel();
        lblTotalAreaStatic = new javax.swing.JLabel();
        lblOutputArea = new javax.swing.JLabel();
        btnCalculateArea = new javax.swing.JButton();
        lblPaintTinsStatic = new javax.swing.JLabel();
        lblOutputPaintTins = new javax.swing.JLabel();
        lblOutputPaintPriceStatic = new javax.swing.JLabel();
        lblOutputPaintPrice = new javax.swing.JLabel();
        lblOutputPaintPriceIncludingVATStatic = new javax.swing.JLabel();
        lblOutputPaintPriceIncludingVAT = new javax.swing.JLabel();
        lblCashTendered = new javax.swing.JLabel();
        txtInputCash = new javax.swing.JTextField();
        lblCostofGoods = new javax.swing.JLabel();
        lblOutputPaintPriceIncludingVAT1 = new javax.swing.JLabel();
        lblOutputCostofGoods = new javax.swing.JLabel();
        btnCalcChange = new javax.swing.JButton();
        lblOutputChange = new javax.swing.JLabel();
        lblChangeAmount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setName("All Paints"); // NOI18N

        txtInputLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputLengthActionPerformed(evt);
            }
        });

        txtInputWidth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputWidthActionPerformed(evt);
            }
        });

        txtInputHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputHeightActionPerformed(evt);
            }
        });

        lblArea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblArea.setText("Enter Measurements below:");

        lblLength.setText("Length");

        lblWidth.setText("Width");

        lblHeight.setText("Height");

        lblTotalAreaStatic.setText("Total Area:");

        btnCalculateArea.setText("Calculate");
        btnCalculateArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateAreaActionPerformed(evt);
            }
        });

        lblPaintTinsStatic.setText("Amount of paint tins needed");

        lblOutputPaintPriceStatic.setText("Total Price of Paint Tins(before VAT) ");

        lblOutputPaintPriceIncludingVATStatic.setText("Total Price of Paint Tins(Including VAT)");

        lblCashTendered.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCashTendered.setText("Cash Tendered:");

        txtInputCash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInputCashKeyPressed(evt);
            }
        });

        lblCostofGoods.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCostofGoods.setText("Total Cost Of Goods");

        btnCalcChange.setText("Calculate Change");
        btnCalcChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcChangeActionPerformed(evt);
            }
        });

        lblChangeAmount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblChangeAmount.setText("Change:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(14, 14, 14))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblLength, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtInputWidth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                        .addComponent(txtInputLength, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtInputHeight))
                                    .addComponent(btnCalculateArea))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblTotalAreaStatic, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPaintTinsStatic)
                                    .addComponent(lblOutputPaintPriceStatic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblOutputPaintPriceIncludingVATStatic))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblOutputPaintPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblOutputPaintTins, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblOutputArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblOutputPaintPriceIncludingVAT, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCashTendered, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtInputCash, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblChangeAmount)
                                .addGap(42, 42, 42)
                                .addComponent(lblOutputChange, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(lblCostofGoods)
                        .addGap(18, 18, 18)
                        .addComponent(lblOutputCostofGoods, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnCalcChange)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(lblOutputPaintPriceIncludingVAT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOutputArea, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(lblPaintTinsStatic)
                            .addComponent(lblOutputPaintTins, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblOutputPaintPriceStatic, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOutputPaintPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOutputPaintPriceIncludingVATStatic, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOutputPaintPriceIncludingVAT, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addComponent(lblOutputPaintPriceIncludingVAT1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLength, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(lblWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(txtInputWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtInputHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTotalAreaStatic, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtInputLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnCalculateArea)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOutputCostofGoods, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCostofGoods, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCashTendered)
                            .addComponent(txtInputCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCalcChange)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblChangeAmount)
                    .addComponent(lblOutputChange, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInputWidthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputWidthActionPerformed
 // TODO add your handling code here:
    }//GEN-LAST:event_txtInputWidthActionPerformed

    private void btnCalculateAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateAreaActionPerformed
int intInput1;
int intInput2;
int intInput3;
int intOutput1;
int intOutput2 = 0;
int intOutput3 = 0;
int intOutput4 = 0;
int intOutput5 = 0;
int intOutput6 = 0;
intInput1 = Integer.parseInt(txtInputLength.getText());
intInput2 = Integer.parseInt(txtInputWidth.getText());
intInput3 = Integer.parseInt(txtInputHeight.getText());
// Formula for Total Surface Area A= 2(height*length)+ 2(height*width) + 2(length*width)
try
{
    intOutput1 = (intInput1 * intInput2) + (intInput2 * intInput3) + (intInput1 * intInput3);
    intOutput2 = 2 * intOutput1;
}
catch (Exception EX)
{
 lblOutputArea.setText("Area cannot be found");
}
finally
{
lblOutputArea.setText(String.valueOf(intOutput2) + " cm2");
}
try 
{
 intOutput3 = intOutput2 / 10;
}
catch (Exception eX)
        {
         lblOutputPaintTins.setText("Values cant be concatenated");  
        }
finally
{
    lblOutputPaintTins.setText((String.valueOf(intOutput3))+ " tins");
}
try
{
  intOutput4 = intOutput3 * 30;  
}
catch(Exception Ex)
{
   lblOutputPaintPrice.setText("Failure to calculate the total price of all paint tins");
}
finally
{
     lblOutputPaintPrice.setText("R " + (String.valueOf(intOutput4)));
}
try
{
//BigDecimal b1 =new BigDecimal("0.15");
double intVAT = 0.15;
intOutput5 = (int) (intOutput4 * intVAT);
intOutput6 = intOutput5 + intOutput4;
}
catch (Exception ex)
    {
    lblOutputPaintPriceIncludingVAT.setText("Error");
    }
finally
{
     lblOutputPaintPriceIncludingVAT.setText(String.valueOf("R" + intOutput6));
}
lblOutputCostofGoods.setText(String.valueOf (intOutput6));//"R" +  
    }//GEN-LAST:event_btnCalculateAreaActionPerformed

    private void btnCalcChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcChangeActionPerformed
int intInput4;
int intInput5;
int intOutput1 = 0;
int intOutput2;
intOutput2 = Integer.valueOf(lblOutputCostofGoods.getText());//Integer.parseInt(lblOutputPaintPriceIncludingVAT));
        intInput4 = Integer.parseInt(txtInputCash.getText());
        intInput5 = intOutput2;
intOutput1 = intInput4 - intInput5;
if (intOutput1 < 0) 
{
JOptionPane.showMessageDialog(null, "Insufficient Cash for Transaction");
}
lblOutputChange.setText(String.valueOf ("R" + intOutput1));//Integer.parseInt(lblOutputCostofGoods);// TODO add your handling code here:
    }//GEN-LAST:event_btnCalcChangeActionPerformed

    private void txtInputLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputLengthActionPerformed

    }//GEN-LAST:event_txtInputLengthActionPerformed

    private void txtInputCashKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputCashKeyPressed

    }//GEN-LAST:event_txtInputCashKeyPressed

    private void txtInputHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputHeightActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_txtInputHeightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcChange;
    private javax.swing.JButton btnCalculateArea;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblCashTendered;
    private javax.swing.JLabel lblChangeAmount;
    private javax.swing.JLabel lblCostofGoods;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblLength;
    private javax.swing.JLabel lblOutputArea;
    private javax.swing.JLabel lblOutputChange;
    private javax.swing.JLabel lblOutputCostofGoods;
    private javax.swing.JLabel lblOutputPaintPrice;
    private javax.swing.JLabel lblOutputPaintPriceIncludingVAT;
    private javax.swing.JLabel lblOutputPaintPriceIncludingVAT1;
    private javax.swing.JLabel lblOutputPaintPriceIncludingVATStatic;
    private javax.swing.JLabel lblOutputPaintPriceStatic;
    private javax.swing.JLabel lblOutputPaintTins;
    private javax.swing.JLabel lblPaintTinsStatic;
    private javax.swing.JLabel lblTotalAreaStatic;
    private javax.swing.JLabel lblWidth;
    private javax.swing.JTextField txtInputCash;
    private javax.swing.JTextField txtInputHeight;
    private javax.swing.JTextField txtInputLength;
    private javax.swing.JTextField txtInputWidth;
    // End of variables declaration//GEN-END:variables

    private int getState(JLabel lblOutputPaintPriceIncludingVAT) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
