/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package textboxlistboxandlist;
    import java.io.File;
    import java.io.FileWriter;
    import java.io.BufferedReader;
    import java.io.FileInputStream;
    import java.io.InputStreamReader;
    import javax.swing.JOptionPane;
    import javax.swing.DefaultListModel;
/**
 *
 * @author CHAD
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddItemToListBox = new javax.swing.JButton();
        btnCreateFile = new javax.swing.JButton();
        btnClearListBox = new javax.swing.JButton();
        btnWriteContent = new javax.swing.JButton();
        btnReadContents = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstList = new javax.swing.JList();
        txtInput = new javax.swing.JTextField();
        lblOutput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAddItemToListBox.setText("Step1: Add Item To List Box");
        btnAddItemToListBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemToListBoxActionPerformed(evt);
            }
        });

        btnCreateFile.setText("Step : Create File");
        btnCreateFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateFileActionPerformed(evt);
            }
        });

        btnClearListBox.setText("Step 4: Clear List Box");
        btnClearListBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearListBoxActionPerformed(evt);
            }
        });

        btnWriteContent.setText("Step 3: Write Contents");
        btnWriteContent.setToolTipText("");
        btnWriteContent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWriteContentActionPerformed(evt);
            }
        });

        btnReadContents.setText("Step 5:Read Content");
        btnReadContents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadContentsActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddItemToListBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReadContents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnWriteContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClearListBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCreateFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddItemToListBox)
                        .addGap(18, 18, 18)
                        .addComponent(btnCreateFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnWriteContent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClearListBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReadContents))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
DefaultListModel<String> dlmList = new DefaultListModel<String>();
    private void btnAddItemToListBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemToListBoxActionPerformed
    dlmList.addElement(txtInput.getText());
    lstList.setModel(dlmList);
    txtInput.setText("");
    txtInput.requestFocusInWindow();// TODO add your handling code here:
    }//GEN-LAST:event_btnAddItemToListBoxActionPerformed

    private void btnCreateFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateFileActionPerformed
File TextFile = new File("textfile.txt");
try
{
    TextFile.createNewFile();
    lblOutput.setText("File has been created");
}// TODO add your handling code here:
catch(Exception Ex)
{
JOptionPane.showMessageDialog(null,lblOutput);
dlmList.removeAllElements();
}
    }//GEN-LAST:event_btnCreateFileActionPerformed

    private void btnWriteContentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWriteContentActionPerformed
int intIndex = lstList.getModel().getSize();

String[] arrSTR = new String[intIndex];
for (int i = 0; i < intIndex; i++)
{
            arrSTR[i]=  (String) lstList.getModel().getElementAt(i);
try
{
    String strfilename="textfile.txt";
                try (FileWriter fw = new FileWriter(strfilename,true)) {
                    fw.write(arrSTR[i]+ "\r\n");
                }
    lblOutput.setText("Content has been written to file");
}
catch (Exception Ex)
{
    JOptionPane.showMessageDialog(null,Ex);
}
}// TODO add your handling code here:
    }//GEN-LAST:event_btnWriteContentActionPerformed

    @SuppressWarnings("empty-statement")
    private void btnReadContentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadContentsActionPerformed
String strline;
BufferedReader brReader = null;
InputStreamReader isrReader = null;
try
{
    try (FileInputStream fisFin = new FileInputStream("textfile.txt")) {
        isrReader = new InputStreamReader(fisFin);
        brReader = new BufferedReader(isrReader);
        while ((strline = brReader.readLine()) != null);
        {
            dlmList.addElement(strline);
            lblOutput.setText("Content has been read from the file");
        }
        brReader.close();
        isrReader.close();
    }
}
catch(Exception Ex)
{
JOptionPane.showMessageDialog(null,Ex);
}
lstList.setModel(dlmList);// TODO add your handling code here:
    }//GEN-LAST:event_btnReadContentsActionPerformed

    private void btnClearListBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearListBoxActionPerformed
dlmList.removeAllElements();        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearListBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItemToListBox;
    private javax.swing.JButton btnClearListBox;
    private javax.swing.JButton btnCreateFile;
    private javax.swing.JButton btnReadContents;
    private javax.swing.JButton btnWriteContent;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JList lstList;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
